### ISSUE TITLE
Problem connecting to local Postgres DB

### ISSUE THREAD

**Issue by madrobby** [chrismccord/labrador#13]
I get this message:

```
`the scheme tcp does not accept registry part: :5432 (or bad hostname?)`
```

My Rails development app works fine tho—what's wrong?

Here's my database.yml:

```
development:
  adapter: postgresql
  encoding: utf8
  database: freckle_092612
  pool: 5
  username: thomas
  password:
  min_messages: warning
```

The error message in Labrador lists password as "!!null"—could that be the problem?
