### ISSUE TITLE
Undefined method 'size' for Postgres connection

### ISSUE THREAD

**Issue by jredburn** [chrismccord/labrador#6]
My app has the following database.yml:

``` yml

---
adapter: postgresql
encoding: unicode
database: dandelion_development
pool: 5
template: template0
host: localhost
port: 5432
```

When starting up, I get "undefined method `size' for nil:NilClass". I tried running `rake test` with an appropriate database.yml in .labrador and got the same message.
